### ISSUE TITLE
Add scrollbar for right side where nodes are displaying

### ISSUE THREAD

**Issue by ishpreetkaurwebner** [jerosoler/Drawflow#139]
Hello @jerosoler ,

Whether there is any way to add scrollbar at right div where we can see nodes and connections. Sometimes, nodes partially or fully hides below the visible area. Whether we can add scrollbar at right end of bordered area?

**Comment by jerosoler** [comment]
Hello @ishpreetkaurwebner 

Try with css: 

```css 
#drawflow {
overflow: auto;
}

.drawflow .connection {
    transform: initial;
}

.drawflow .connection .main-path {
    transform: initial;
}
```

I think that could work
