### ISSUE TITLE
How to add simple straight verticle line as widget?

### ISSUE THREAD

**Issue by princeyogesh** [jerosoler/Drawflow#158]
I want just simple streight line in widget bar , but whenever i try to pull in it appears inside the box what way should i proceed to use api? 
here are the code snippets and output i am gettign 

![image](https://user-images.githubusercontent.com/29053720/115012334-58c93e00-9ecd-11eb-908f-fa2e584bea0a.png)
![image](https://user-images.githubusercontent.com/29053720/115012438-74344900-9ecd-11eb-86d8-b7d3df1c0b8b.png)
![image](https://user-images.githubusercontent.com/29053720/115012877-f7559f00-9ecd-11eb-9c32-ca348fb7a498.png)

**Comment by princeyogesh** [comment]
I want line should have output bubble , but here i am getting box in addition and output bubble is on the box

**Comment by jerosoler** [comment]
I don't quite understand you.

Can you draw a picture of what you want?

**Comment by princeyogesh** [comment]
@jerosoler  please see the below sketch 
something like this i want to achive for call flows, I just need help how can i draw the red line as shown in image.

![image](https://user-images.githubusercontent.com/29053720/115025686-49eb8700-9edf-11eb-92cf-2d80a5747189.png)

**Comment by jerosoler** [comment]
Hello,

I think you want to do something like this:
https://bramp.github.io/js-sequence-diagrams/

I don't know if this is the right library for this. I'm not sure what you want to do.

I show you how you can create the node of user A.

![image](https://user-images.githubusercontent.com/30957047/115044975-54ede980-9ed6-11eb-9b66-64933716238e.png)

Javascript
```javascript 
  editor.addNode('usera', 1, 1, 150, 300, 'usera', {}, `User A`);
```
CSS
```css
      .drawflow-node.usera {
        width: 6px;
        height: 300px;
        padding: 0px;
        background: red;
        border: 0px;
      }

      .drawflow-node.usera .drawflow_content_node {
        position: absolute;
        top: -30px;
        width: 100px;
        left: -20px;
      }
      .drawflow-node.usera .outputs{
        position: absolute;
        top: 50px;
        left: -12.5px;
      }

      .drawflow-node.usera .inputs{
        position: absolute;
        top: 200px;
        right: -12.5px;
      }
```
Jero
