### ISSUE TITLE
how to change input /output bubble to triangle shape

### ISSUE THREAD

**Issue by princeyogesh** [jerosoler/Drawflow#163]

**Comment by jerosoler** [comment]
Hello @princeyogesh 

Edit with css
```css
.drawflow .drawflow-node .input {
 // Your triangle shape
}
.drawflow .drawflow-node .output {
// Your triangle shape
}
```

**Comment by princeyogesh** [comment]
@jerosoler  i tried this this not works, when i used square shape, this gives something like this 
![image](https://user-images.githubusercontent.com/29053720/116345026-f5140e80-a804-11eb-8b34-fa463eb200db.png)

![image](https://user-images.githubusercontent.com/29053720/116345078-14ab3700-a805-11eb-9013-f0315d55a40a.png)

**Comment by jerosoler** [comment]
Simple example edit demo in browser:

![image](https://user-images.githubusercontent.com/30957047/116357624-f6413d80-a7fc-11eb-8529-0a2ece04e4f3.png)


```css
.drawflow .drawflow-node .input {
    left: -10px;
    background: transparent;
}
.drawflow .drawflow-node .output {
    right: 0px;
}
.drawflow .drawflow-node .input, .drawflow .drawflow-node .output {
    /* height: 15px; */
    /* width: 15px; */
    /* border: 2px solid var(--border-color); */
    width: 0;
    height: 0;
    border-style: solid;
    border-width: 15px 0 15px 15px;
    border-color: transparent transparent transparent #007bff;
    background: transparent;
    border-radius: 0px;
}
```
