### ISSUE TITLE
Label for connector lines

### ISSUE THREAD

**Issue by taroongunessee** [jerosoler/Drawflow#18]
Hello, is it possible to add labels to connector lines? For example, Yes/No or If/Else?

**Comment by jerosoler** [comment]
Hi! 

I'ts possible with css:
![image](https://user-images.githubusercontent.com/30957047/89006717-a71aba80-d307-11ea-930a-ef658b90ffc9.png)

For example: 
```css
.drawflow-node.multiple .outputs .output:nth-child(1):before {
    display: block;
    content: "Yes";
    position: relative;
    right: 30px;
  }
 .drawflow-node.multiple .outputs .output:nth-child(2):before {
    display: block;
    content: "No";
    position: relative;
    right: 30px;
 }
```

In case use the classname "multiple"

editor.addNode(name, inputs, outputs, posx, posy, **class**, data, html);

Does the solution work for you?
