### ISSUE TITLE
Misaligned routes when chrome zoom is not 100%

### ISSUE THREAD

**Issue by TLeiter** [jerosoler/Drawflow#218]
When user has a different zoom factor in Chrome, the routes are not alligned.

The following example was done with the demo application:

![2021-07-26 09_22_15-Clipboard](https://user-images.githubusercontent.com/87968153/126948980-99581d52-886e-4dd4-b987-0cb1472dd517.png)

**Comment by jerosoler** [comment]
Uhmmm. What is your version of crhome?

![image](https://user-images.githubusercontent.com/30957047/126950340-ac5799cf-4247-4d22-81e1-7768e4f7f615.png)

**Comment by TLeiter** [comment]
Last one Version 92.0.4515.107 (Official Build) (64-bit)

**Comment by TLeiter** [comment]
Zoom at 150% works fine, but 125% not.

**Comment by jerosoler** [comment]
Work in 125% 

![image](https://user-images.githubusercontent.com/30957047/126983705-66755084-e92b-4d6c-ae3a-ce9aab29bc87.png)


This I think could be due to a browser problem rather than a library problem.

With the library you can set a zoom.

**Comment by Fr1411** [comment]
i have the same problem with chrome Versión 92.0.4515.107 (Build oficial).
No zoom.

![image](https://user-images.githubusercontent.com/88341979/127902214-f1de4d33-fc6d-4c54-9157-b6db92cdd293.png)

zoom 80% its works
![image](https://user-images.githubusercontent.com/88341979/127902295-9443f66c-f80e-42e3-a3ca-6d9d62c0f3c0.png)

**Comment by jerosoler** [comment]
@Fr1411 
If you move any node, are they still wrong?

I see the images of the demo.
The same thing happens without the demo.

**Comment by jerosoler** [comment]
I just installed the latest version and I see that it also happens.

![image](https://user-images.githubusercontent.com/30957047/127912449-22b8d8e6-b683-4ddc-b562-2520a0b038cd.png)

**Comment by Fr1411** [comment]
@jerosoler yes! if i move any node it´s the same.
In my project the situation is equal
![image](https://user-images.githubusercontent.com/88341979/127987266-35e19fab-c17f-4b1d-819c-c4988e2b5a0c.png)

**Comment by Fr1411** [comment]
@jerosoler Do you think this problem will be solved?

**Comment by Ammy22** [comment]
Temporary fix is ->
<meta name="viewport" content="width=device-width, initial-scale=.8">

**Comment by jerosoler** [comment]
Fix in new version 0.0.48 https://github.com/jerosoler/Drawflow/releases/tag/0.0.48

Removed transform tranlate from connection. 

The new css looks like this:

```css
.drawflow .connection {
  position: absolute;
  pointer-events: none;
}
.drawflow .connection .main-path {
  fill: none;
  stroke-width: 5px;
  stroke: steelblue;
  pointer-events: all;
}
.drawflow .connection .main-path:hover {
  stroke: #1266ab;
  cursor: pointer;
}

.drawflow .connection .main-path.selected {
  stroke: #43b993;
}

.drawflow .connection .point {
  cursor: move;
  stroke: black;
  stroke-width: 2;
  fill: white;
  pointer-events: all;
}
```

Update Demo page
