### ISSUE TITLE
I can't get Drawflow to work

### ISSUE THREAD

**Issue by jeison0894** [jerosoler/Drawflow#361]
First of all amazing project friend!. My problem is that I want to use your dependency for a project but I've tried everything and it doesn't work for me, I've already tried with CDN, with npm, cloning the repo, but I always get a blank div, what am I doing wrong? If you could help me, thank you very much.

https://codesandbox.io/s/recursing-fog-t6fjry?file=/index.html

**Comment by jerosoler** [comment]
Hi! Thanks!

View minium example: https://github.com/jerosoler/Drawflow/issues/316#issuecomment-985282224
It seems that you are missing the style of the div.
```css
#drawflow { 
      position: relative;
      text-align:initial;
      width: 100%;
      height: 800px;
      border: 1px solid red;
}
```

You can also see the demo that goes by cdn.
https://github.com/jerosoler/Drawflow/blob/master/docs/index.html

Jero
