### ISSUE TITLE
Delete icon

### ISSUE THREAD

**Issue by cage81** [jerosoler/Drawflow#47]
Hi, I would like to be able to show a custom delete icon (like a trash icon or something else ,for nodes and connections) and also to be able to show it on node/connection selection (not in contextmenu). 

I'm working with VueJS, can you help me about those features? Thanks for your work!

**Comment by jerosoler** [comment]
Hello @cage81 

You have multiple options to do it.

For example simulate second button and edit with css the class `.drawflow-delete`
```javascript
editor.on("click", function(e) {
      if(e.target.classList[0] === "drawflow-node" || e.target.closest(".drawflow_content_node") || e.target.classList[0] === "main-path") {
        setTimeout(function(){
          editor.contextmenu(e);
        },25);

      }
    });
```

```css 
.drawflow-delete {
    background: transparent;
    border: 1px solid red;
    width: 20px;
    height: 20px;
  }
```
Add background-image or icon with style.


### Other options

Use methods https://github.com/jerosoler/Drawflow#methods `removeNodeId(id)` and `removeSingleConnection(id_output, id_input, output_class, input_class)`

Does any of these options work for you?
