### ISSUE TITLE
Change z-index of outputs

### ISSUE THREAD

**Issue by umnibot** [jerosoler/Drawflow#614]
I have commented the z-index in `drawflow .drawflow-node` class

```
.drawflow .drawflow-node {
     //z-index: initial;
}
```
But somehow now the connection line for outputs goes inside the node.

![image](https://user-images.githubusercontent.com/45895973/207638054-1bb37319-670c-4c3c-b38d-954702944114.png)

Somewhere I read that the z-index for nodes by default is 2, so I have tried adding

```
.connection {
     z-index: 3;
}
```

and also 

```
.main-path {
     z-index: 3;
}
```
as well as 

```
.drawflow .connection .main-path {
     z-index: 3;
}
```

but none of it worked.

How can I make the connection lines go over the nodes?

**Comment by jerosoler** [comment]
Try:
```css
    .drawflow .drawflow-node {
        /*z-index: initial;  */
    }
    
    .drawflow svg {
        z-index: 2;
    }
    .drawflow .drawflow-node .input {
        z-index: 3;
    }

   /* Fix for create connection */
    .drawflow > [class="connection"] .main-path {
        pointer-events:none;
    }
```

**Comment by jerosoler** [comment]
Only this is needed:
```css
    .drawflow svg {
        z-index: 2;
    }
    .drawflow > [class="connection"] .main-path {
        pointer-events:none;
    }
```
