### ISSUE TITLE
Enabling dark mode 

### ISSUE THREAD

**Issue by anish97IND** [jerosoler/Drawflow#69]
Hi, Is there way where we can toggle between dark mode and light mode to make things more user friendly.

**Comment by jerosoler** [comment]
Hello @anish97IND 

Use the css custom variables for create dark mode theme.
```css
:root {
  --dfNodeBackgroundColor: #000000;
}
:root.dark-mode { 
 --dfNodeBackgroundColor: #FFFFFF;
}

.drawflow .drawflow-node {
  background: var(--dfNodeBackgroundColor);
}
```
You can use the theme generator that exports the code with custom variables https://jerosoler.github.io/drawflow-theme-generator/

View tutorial dark mode with css variables: https://dev.to/ananyaneogi/create-a-dark-light-mode-switch-with-css-variables-34l8

I hope it helps you.
