### ISSUE TITLE
Animation line connection

### ISSUE THREAD

**Issue by adrielov** [jerosoler/Drawflow#748]
I would like to know how to add a directional movement animation to the connecting lines...
something like the example below.

https://codesandbox.io/s/4qrdpd?file=/DownloadButton.js&utm_medium=sandpack
https://reactflow.dev/docs/examples/misc/download-image/

**Comment by jerosoler** [comment]
Simple add in css:

```css
    .drawflow .connection .main-path {
      stroke-dasharray: 5;
      animation: dashdraw .5s linear infinite;
    }
    @keyframes dashdraw {
    0% {
        stroke-dashoffset: 10
      }
    }
```
