### ISSUE TITLE
onClick on stroke of the path

### ISSUE THREAD

**Issue by hyminhlee** [jerosoler/Drawflow#796]
Hi @jerosoler 
Can I catch the event by clicking on the stroke (red) instead of all path content (black color)?
If Connectors are overlapping, it is hard to select one of them
![path](https://github.com/jerosoler/Drawflow/assets/56029499/6b353e7e-546c-40af-bc0a-5b04cd68b262)

**Comment by jerosoler** [comment]
Try css:
```css
.drawflow .connection .main-path {
   pointer-events: stroke;
}
```
