### ISSUE TITLE
Is there a way to display drawflow-delete icon permanently on nodes?

### ISSUE THREAD

**Issue by VK-Devloper** [jerosoler/Drawflow#80]
How can i display x icon without selecting node?

**Comment by VK-Devloper** [comment]
![icon](https://user-images.githubusercontent.com/63523860/100440599-2a3bf980-30cb-11eb-8761-d61badc4fa69.png)

**Comment by jerosoler** [comment]
Simple with css:
```css
.parent-node .drawflow-delete {
    display: none !important;
}
```
