### ISSUE TITLE
`.drawflow-node` with style: `width: auto` doesn't like leaving `.drawflow`

### ISSUE THREAD

**Issue by bennetgallein** [jerosoler/Drawflow#818]
As the title says, having the `.drawflow-node` class with `width: auto` instead of a fixed width, dragging it outside of the `.drawflow` class compresses the width.

![chrome-capture-2024-1-31-min](https://github.com/jerosoler/Drawflow/assets/15325891/d8f8b8bc-020d-483a-b70e-2380d94b51c0)

any help is appreciated :pray:

**Comment by bennetgallein** [comment]
Hey,

I've copied your snippet and ran it locally.

![chrome-capture-2024-2-1](https://github.com/jerosoler/Drawflow/assets/15325891/c8333668-ff0c-4dd9-b8b9-0326b1b8896d)

Browser is Chrome 120 but also reproducable in Firefox 115.

Since you've only posted a picture I want to clarify that this is happening when you drag the box to the side of the canvas.

**Comment by jerosoler** [comment]
Try new snippet.

Only added new css:

```css
 #drawflow {
      position: relative;
      width: 100%;
      height: 800px;
      border: 1px solid red;
    }
    .drawflow, .drawflow .parent-node {
      position:absolute;
    }

    .drawflow .drawflow-node {
      width: auto;
      position: relative;
    }
```

Complet example:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.css" />
  <script src="https://cdn.jsdelivr.net/gh/jerosoler/Drawflow/dist/drawflow.min.js"></script>
  <style>
    #drawflow {
      position: relative;
      width: 100%;
      height: 800px;
      border: 1px solid red;
    }
    .drawflow, .drawflow .parent-node {
      position:absolute;
    }

    .drawflow .drawflow-node {
      width: auto;
      position: relative;
    }
  </style>
</head>
<body>
  <div>
    <div id="drawflow"></div>
  </div>
  <script>
    var id = document.getElementById("drawflow");
    const editor = new Drawflow(id);
    editor.start();  
    editor.addNode("item", 1, 1, 100, 550, "item", {}, 'Hi!');
    editor.addNode("item", 1, 1, 300, 550, "item", {}, 'Large element');
    editor.addNode("item", 1, 1, 500, 550, "item", {}, 'Extra Large element!!! asda asdsad sadsa dsadsasad sadsadsadsad  sadas');
  </script>
</body>
</html>
```
