### ISSUE TITLE
How to adjust the position of the connection when node resizes?

### ISSUE THREAD

**Issue by meet1919** [jerosoler/Drawflow#834]
The node which I am using has the following css
```css
.drawflow .drawflow-node {
    width: auto;
    height: auto;   
}

.drawflow .drawflow-node .input,
.drawflow .drawflow-node .output {
    height: 15px;
    width: 15px;
    border: 2px solid var(--border-color);
}

.drawflow .drawflow-node .input:hover,
.drawflow .drawflow-node .output:hover {
    background: #4ea9ff;
}

.drawflow .drawflow-node .output {
    right: 0;
    transform: translateX(-50%);
}

.drawflow .drawflow-node .input {
    left: 0px;
    transform: translateX(-50%);
    background: #43b993;
}
```

when the node resizes the `input` and `output` are shifted also as they should be at the vertical center of the node. But the thing is connection doesn't shift. It attaches/shifts instantly to the `input` and `output` when I drag the node.  

the problem occurs here
```html
<svg class="connection node_in_node-2 node_out_node-1 output_1 input_1 p-task">
    <path class="main-path" d=" M 399.2000043392181 400.3000259399413 C 478.993762731552 400.3000259399413 
        478.993762731552 275.349998474121 558.787521123886  275.349998474121"></path>
</svg>
```

the `d` attribute  of path should dynamically update when node resizes.
